import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body style={{ margin: 0, padding: 0, paddingTop: "70px" }}>
        <Header first_name="太郎" last_name="鈴木" Todos={[]} />
        <div style={{ display: "flex", minHeight: "100vh" }}>
          <Sidebar />
          <div style={{ marginLeft: "250px", width: "calc(100% - 250px)" }}>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
